### ISSUE TITLE
Ignition Edge License

### ISSUE THREAD

**Issue by chrisegge** [IgnitionModuleDevelopmentCommunity/IgnitionNode-RED#3]
It was working great until I moved the Raspberry Pi i had it running on and rebooted it. Now the module has disappeared in Ignition and it says that it is "Faulted Unlicensed for Edge". In the other device running Node-Red I getting this error message "JSON error: SyntaxError: Unexpected token < in JSON at position 0". Your help would be really great right now. I just finished setting up 3 different Raspberry Pi's with remote IO that we were going to test.

**Comment by chrisegge** [comment]
com.inductiveautomation.ignition.common.modules.ModuleLoadException: Unlicensed module "Ignition Node-RED Module" cannot run on licensed Edge Gateway
	at com.inductiveautomation.ignition.gateway.modules.ModuleManagerImpl$LoadedModule.<init>(ModuleManagerImpl.java:1861)
	at com.inductiveautomation.ignition.gateway.modules.ModuleManagerImpl$LoadedModule.<init>(ModuleManagerImpl.java:1788)
	at com.inductiveautomation.ignition.gateway.modules.ModuleManagerImpl.loadModule(ModuleManagerImpl.java:1202)
	at com.inductiveautomation.ignition.gateway.modules.ModuleManagerImpl.loadModuleInternal(ModuleManagerImpl.java:1125)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

7.9.10 (b2018112821)
Oracle Corporation 1.8.0_65


This is the full fault message if it helps at all
