### ISSUE TITLE
Internal error when creating new Node-Red API token

### ISSUE THREAD

**Issue by tedwad** [IgnitionModuleDevelopmentCommunity/IgnitionNode-RED#37]
I have successfully installed the Node Red module (version 1.5.15) to my Ignition Gateway (version 8.1.25) which is on an Nvidia Jetson TX2 running Ubuntu 18.04. I then tried to create a new API token with the below configuration: 
![IgnitionNodeRedConfig](https://github.com/IgnitionModuleDevelopmentCommunity/IgnitionNode-RED/assets/89061708/71649a30-01cb-4af8-aae5-1e90c469f059)

However, when I select the "Create New Node-Red API Token" button, I get an internal error on the gateway webpage, as shown here:
![IgnitionNodeRedInternalError](https://github.com/IgnitionModuleDevelopmentCommunity/IgnitionNode-RED/assets/89061708/3e10dd81-28d8-4d19-ae9a-1fb780ce2996)

I haven't seen this issue reproduced from what I've seen online, and I'm not sure what is causing my error. Does anyone have any suggestions?

**Comment by iatraviscox** [comment]
Can you check the logs in the status page to find the error? You can either post the a screenshot or copy/paste the error details.

**Comment by tedwad** [comment]
Here are the logs from the gateway, after restarting the gateway and trying to create the Node-RED API Token twice. The DefaultExceptionMapper is triggered whenever I try to create the Node-Red API Token.

![image](https://github.com/IgnitionModuleDevelopmentCommunity/IgnitionNode-RED/assets/89061708/b6c31535-0fc8-4a8d-935e-cb5502fd9b47)

**Comment by iatraviscox** [comment]
Sorry but can you expand the error (plus icon) to get the details?

**Comment by tedwad** [comment]
Sorry yes, here are the expanded log details for that error:
```
org.apache.wicket.WicketRuntimeException: Method onFormSubmitted of interface org.apache.wicket.markup.html.form.IFormSubmitListener targeted at [CsrfPreventingForm [Component id = form]] on component [CsrfPreventingForm [Component id = form]] threw an exception
at org.apache.wicket.RequestListenerInterface.internalInvoke(RequestListenerInterface.java:268)
at org.apache.wicket.RequestListenerInterface.invoke(RequestListenerInterface.java:216)
at org.apache.wicket.core.request.handler.ListenerInterfaceRequestHandler.invokeListener(ListenerInterfaceRequestHandler.java:243)
at org.apache.wicket.core.request.handler.ListenerInterfaceRequestHandler.respond(ListenerInterfaceRequestHandler.java:236)
at org.apache.wicket.request.cycle.RequestCycle$HandlerExecutor.respond(RequestCycle.java:890)
at org.apache.wicket.request.RequestHandlerStack.execute(RequestHandlerStack.java:64)
at org.apache.wicket.request.cycle.RequestCycle.execute(RequestCycle.java:261)
at org.apache.wicket.request.cycle.RequestCycle.processRequest(RequestCycle.java:218)
at org.apache.wicket.request.cycle.RequestCycle.processRequestAndDetach(RequestCycle.java:289)
at org.apache.wicket.protocol.http.WicketFilter.processRequestCycle(WicketFilter.java:259)
at org.apache.wicket.protocol.http.WicketFilter.processRequest(WicketFilter.java:201)
at org.apache.wicket.protocol.http.WicketFilter.doFilter(WicketFilter.java:282)
at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:210)
at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:527)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:131)
at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:578)
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:223)
at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1570)
at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1384)
at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1543)
at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1306)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
at com.inductiveautomation.catapult.handlers.RemoteHostNameLookupHandler.handle(RemoteHostNameLookupHandler.java:121)
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:301)
at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:51)
at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:141)
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
at org.eclipse.jetty.server.Server.handle(Server.java:563)
at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:505)
at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:762)
at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:497)
at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282)
at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:558)
at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:379)
at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:146)
at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:416)
at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:385)
at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:272)
at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:140)
at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException: null
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.apache.wicket.RequestListenerInterface.internalInvoke(RequestListenerInterface.java:258)
... 55 common frames omitted
Caused by: simpleorm.utils.SException$Validation: Field [F NodeREDAPITokens.APIToken] value must be alphanumeric
at org.imdc.nodered.NodeREDAPITokens$1.onValidate(NodeREDAPITokens.java:32)
at simpleorm.dataset.SFieldMeta.doValidate(SFieldMeta.java:294)
at simpleorm.dataset.SRecordInstance.doValidateField(SRecordInstance.java:940)
at simpleorm.dataset.SRecordInstance.setObject(SRecordInstance.java:291)
at simpleorm.dataset.SRecordInstance.setObject(SRecordInstance.java:248)
at com.inductiveautomation.ignition.gateway.web.models.FieldModel.setObject(FieldModel.java:144)
at org.apache.wicket.Component.setDefaultModelObject(Component.java:3053)
at org.apache.wicket.markup.html.form.FormComponent.setModelObject(FormComponent.java:1577)
at org.apache.wicket.markup.html.form.FormComponent.updateModel(FormComponent.java:1098)
at org.apache.wicket.markup.html.form.Form$FormModelUpdateVisitor.component(Form.java:230)
at org.apache.wicket.markup.html.form.Form$FormModelUpdateVisitor.component(Form.java:200)
at org.apache.wicket.util.visit.Visits.visitPostOrderHelper(Visits.java:274)
at org.apache.wicket.util.visit.Visits.visitPostOrderHelper(Visits.java:262)
at org.apache.wicket.util.visit.Visits.visitPostOrderHelper(Visits.java:262)
at org.apache.wicket.util.visit.Visits.visitPostOrderHelper(Visits.java:262)
at org.apache.wicket.util.visit.Visits.visitPostOrderHelper(Visits.java:262)
at org.apache.wicket.util.visit.Visits.visitPostOrderHelper(Visits.java:262)
at org.apache.wicket.util.visit.Visits.visitPostOrder(Visits.java:245)
at org.apache.wicket.markup.html.form.FormComponent.visitComponentsPostOrder(FormComponent.java:424)
at org.apache.wicket.markup.html.form.Form.internalUpdateFormComponentModels(Form.java:1860)
at org.apache.wicket.markup.html.form.Form.updateFormComponentModels(Form.java:1825)
at org.apache.wicket.markup.html.form.Form.process(Form.java:956)
at org.apache.wicket.markup.html.form.Form.onFormSubmitted(Form.java:789)
at org.apache.wicket.markup.html.form.Form.onFormSubmitted(Form.java:701)
... 60 common frames omitted
```

**Comment by iatraviscox** [comment]
Ok I need to fix that. You just need to make sure the API token is alphanumeric with no spaces (just letters and numbers).

**Comment by tedwad** [comment]
Awesome, I just took out the exclamation point and it worked, thank you so much!
